---
- name: Terminate tagged instances
  hosts: tag_project_multi_vpc
  gather_facts: false
  remote_user: ec2-user
  tasks:
    - meta: refresh_inventory
    - ec2:
        state: absent
        region: us-east-2
        instance_ids: "{{ ec2_id }}"
      delegate_to: localhost
